name: Tests

on: push

jobs:
  launch-tests:
    runs-on: ubuntu-latest
    container:
      image: openjdk:8-jdk-alpine
    steps:
      - uses: actions/checkout@v3

      - name: Give execute permission to Maven wrapper
        run: chmod +x ./mvnw

      - name: Launch tests with Maven
        run: ./mvnw test
